# Generated by Django 2.2.1 on 2020-11-10 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ecole', models.CharField(blank=True, help_text='Ex: Université Nangui Abrogoua', max_length=100)),
                ('niveau', models.CharField(blank=True, choices=[('Licence_1', 'Licence 1'), ('Prem_anne', '1ère année'), ('Licence_2', 'Licence 2'), ('Deux_anne', '2ième année'), ('AS', 'AS'), ('ITS', 'ITS'), ('ISE', 'ISE'), ('Licence_3', 'Licence 3'), ('Troi_anne', '3ième année'), ('Master_1', 'Master 1'), ('Quatre_anne', '4ième année'), ('Master_2', 'Master 2'), ('Cinq_anne', '5ième année'), (' Doct', 'Doctorant')], max_length=30)),
                ('profession', models.CharField(blank=True, max_length=30)),
                ('DomainDePredilection', models.CharField(blank=True, max_length=30)),
                ('Bio', models.TextField(blank=True, help_text="Ex: Etudiant (Ingenieur Informatique...) en master de science politique à l'université Felix Houphouet Boigny", max_length=500)),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
