# Generated by Django 2.2.1 on 2020-10-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201021_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name="niveau d'etude",
            field=models.CharField(blank=True, choices=[('Licence_1', 'Licence 1'), ('Prem_anne', '1ère année'), ('Licence_2', 'Licence 2'), ('Deux_anne', '2ième année'), ('AS', 'AS'), ('ITS', 'ITS'), ('ISE', 'ISE'), ('Licence_3', 'Licence 3'), ('Troi_anne', '3ième année'), ('Master_1', 'Master 1'), ('Quatre_anne', '4ième année'), ('Master_2', 'Master 2'), ('Cinq_anne', '5ième année'), (' Doct', 'Doctorant')], max_length=30),
        ),
    ]
