# Generated by Django 2.2.1 on 2020-10-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201022_0607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name="niveau d'etude",
            new_name='niveau',
        ),
    ]
