# Generated by Django 2.2.1 on 2020-11-10 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum', models.CharField(choices=[('Info generale', 'Info generale'), ('Anglais', 'Anglais'), ('Allemand', 'Allemand'), ('Droit', 'Droit'), ('Espagnol', 'Espagnol'), ('Geographie', 'Geographie'), ('Histoire', 'Histoire'), ('Lettre moderne', 'Lettre moderne'), ('Philosophie', 'Philosophie'), ('Math Info', 'Math Info'), ('Medecine', 'Medecine'), ('Odonto', 'Odonto'), ('Pharmacie', 'Pharmacie'), ('Physique Chimie', 'Physique Chimie'), ('Strm CBG', 'Strm CBG'), ('Science Economie', 'Science Economie'), ('Arts plastiques', 'Arts plastiques'), ('Musique', 'Musique'), ('SN', 'Science de la nature:SN'), ('SFA', 'Science fondamentale:SFA'), ('SGE', "Science de gestion de l'env:SGE"), ('ENS', 'Ecole normale sup:ENS'), ('ENSEA', 'Ecole de statistique:ENSEA'), ('INPHB', 'Polytechnique:INPHB')], max_length=30)),
                ('titre', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField()),
                ('contenu', models.TextField()),
                ('cover', models.ImageField(default='defaultP.png', upload_to='images_p')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='blog_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('publie', models.DateTimeField(auto_now_add=True)),
                ('activate', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
