# Generated by Django 2.2.1 on 2020-10-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='auteur',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
