# Generated by Django 2.2.1 on 2020-10-07 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201001_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='forum',
            field=models.CharField(blank=True, choices=[('INFO', 'Info-Publique'), ('MI', 'Math-Info'), ('HIST', 'Histoire'), ('Geo', 'Geographie'), ('MED', 'Medecine'), ('PC', 'Physique-Chimie'), ('STRM', 'Strm-Cbg'), ('S-ECO', 'Science-Eco'), ('ANG', 'Anglais'), ('DROIT', 'Droit'), ('All', 'Allemand'), ('ESPA', 'Espagnole'), ('PHILO', 'Philosophie')], max_length=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
