# Generated by Django 2.2.1 on 2020-10-14 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201009_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum', models.CharField(choices=[('INFO', 'Info-Publique'), ('MI', 'Math-Info'), ('HIST', 'Histoire'), ('Geo', 'Geographie'), ('MED', 'Medecine'), ('PC', 'Physique-Chimie'), ('STRM', 'Strm-Cbg'), ('S-ECO', 'Science-Eco'), ('ANG', 'Anglais'), ('DROIT', 'Droit'), ('All', 'Allemand'), ('ESPA', 'Espagnole'), ('PHILO', 'Philosophie')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Forum'),
        ),
    ]
