# Generated by Django 2.2.1 on 2020-10-16 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201014_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='forum',
            field=models.CharField(choices=[('Info generale', 'Info generale'), ('Anglais', 'Anglais'), ('Allemand', 'Allemand'), ('Droit', 'Droit'), ('Espagnol', 'Espagnol'), ('Geographie', 'Geographie'), ('Histoire', 'Histoire'), ('Lettre moderne', 'Lettre moderne'), ('Philosophie', 'Philosophie'), ('Math Info', 'Math Info'), ('Medecine', 'Medecine'), ('Odonto', 'Odonto'), ('Pharmacie', 'Pharmacie'), ('Physique Chimie', 'Physique Chimie'), ('Strm CBG', 'Strm CBG'), ('Science Economie', 'Science Economie'), ('Arts plastiques', 'Arts plastiques'), ('Musique', 'Musique'), ('SN', 'Science de la nature:SN'), ('SFA', 'Science fondamentale:SFA'), ('SGE', "Science de gestion de l'env:SGE"), ('ENS', 'Ecole normale sup:ENS'), ('ENSEA', 'Ecole de statistique:ENSEA'), ('INPHB', 'Polytechnique:INPHB')], max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
